### ISSUE TITLE
Setuptools 61 breaks imports

### ISSUE THREAD

**Issue by timkpaine** [jupyter/jupyter-packaging#130]
StaticModule is removed/not exposed in the same place
https://github.com/jupyter/jupyter-packaging/blob/92c800411399324a462208091fd294d3863328a5/jupyter_packaging/setupbase.py#L37

**Comment by timkpaine** [comment]
https://github.com/pypa/setuptools/commit/49b7a60050836868ecd63dc38ad0729626a356f3

**Comment by abravalheri** [comment]
Sorry guys, I moved this file to be possible to use it for both `setup.cfg` and `pyproject.toml`
