### ISSUE TITLE
Version 0.12.0 installs tests directly into site-packages

### ISSUE THREAD

**Issue by frenzymadness** [jupyter/jupyter-packaging#134]
It seems that because `tests` folder is now a Python package (see the new `__init__.py` in https://github.com/jupyter/jupyter-packaging/commit/d56a2dedbf14324d1f783c1d8f2df256942ac64b) the folder is included in the release. This means that the tests are also installed and they are installed directly into `site-packages` folder, which is not correct I'd say.
```
$ ls lib/python3.10/site-packages/tests 
conftest.py        test_core_functions.py     test_install.py            utils.py
__init__.py        test_datafiles_install.py  test_is_stale.py
__pycache__        test_datafiles_paths.py    test_main.py
test_build_api.py  test_deprecated.py         test_utility_functions.py
```
Is there any reason to have tests being a part of the released code? If so, would it make sense to move them somewhere else?

**Comment by blink1073** [comment]
Fixed by #135
