### ISSUE TITLE
Install failure - AttributeError: 'Distribution' object has no attribute 'set_defaults'

### ISSUE THREAD

**Issue by icanhasmath** [jupyter/jupyter-packaging#143]
For nix/windows installs I'm running into this error on install:

```
  File "C:\builds\deps\5d2381d4-86ec-5e0b-90ef-e24dd41d5457\installdir\lib\site-packages\setuptools\config\expand.py", line 415, in __exit__
    self._dist.set_defaults.analyse_name()  # Now we can set a default name
AttributeError: 'Distribution' object has no attribute 'set_defaults'
```
When using setuptools 61 or greater.

This section of code was introduced at version 61:
https://github.com/pypa/setuptools/blob/4923d1139be9366b3010a6d6e56d4c4980a0ab6e/setuptools/config/expand.py#L407

**Comment by blink1073** [comment]
Hi @icanhasmath, we're not calling that API directly as far as I know, does this happen if you use the setuptools backend?  If so, can you please report on the setuptools repo?

**Comment by icanhasmath** [comment]
I believe this is using the `setuptools.build_meta` build backend.  I can report the issue with them.

**Comment by blink1073** [comment]
Great, thanks!
