### ISSUE TITLE
Feat: move to hatchling?

### ISSUE THREAD

**Issue by agoose77** [jupyter/jupyter-packaging#145]
I am aware that @blink1073 has been looking into using hatch for building e.g. nbconvert.

I've also used it to write my own build plugin, and it's very easy to use. Given that hatch already supports PEP 621, PEP 517, PEP 660 et al, we'd be getting a lot of nice features up front. 

Relevant Issues:
- https://github.com/jupyter/jupyter-packaging/issues/103
- https://github.com/jupyter/jupyter-packaging/issues/119
- https://github.com/jupyter/jupyter-packaging/issues/122

**Comment by blink1073** [comment]
Hi @agoose77, actually already testing out a plugin in https://github.com/jupyter/notebook/pull/6425.  My goal is indeed to have that replace our use of jupyter-packaging across the board.

**Comment by blink1073** [comment]
cf https://github.com/jupyterlab/team-compass/issues/146

**Comment by ofek** [comment]
This is done I think

**Comment by jasongrout** [comment]
Just to be clear, if the hatch solution pans out, is the plan to sunset this project and eventually archive it?

**Comment by blink1073** [comment]
> Just to be clear, if the hatch solution pans out, is the plan to sunset this project and eventually archive it?

Yes, that is correct

**Comment by ofek** [comment]
Has the blog post been released yet?

**Comment by blink1073** [comment]
Not yet 😅.  I'm tracking the migration effort in https://github.com/jupyterlab/hatch-jupyter-builder/issues/54
