### ISSUE TITLE
How is this repo intended to be used?

### ISSUE THREAD

**Issue by mpacer** [jupyter/jupyter-packaging#23]
@ian-r-rose and I are looking to release jupyterlab-latex which is python 3.6+ only. 

While I was building some of the version checking based on the IPython repo, Ian pointed out that this repo existed and we might be able to use common tooling. He pointed out that a few repos use a `setupbase.py` similar to the one here.

Currently the README says to `pip install jupyter-packaging` and then doesn't quite say how to use the package after it has been installed. We looked at the `__main__` and noticed that that would seem to do the necessary copying so that 

> The contents of jupyter_packaging.py are copied locally to setupbase.py so they are available to run the setup.py script itself

But then, after installing from pypi,  `python -m jupyter_packaging` did seemingly nothing.

It could be possible that we're supposed to copy the `setupbase.py` directly… but in that case I can't tell what the advantage of having jupyter-packaging in a package is. 

Could we get some guidance on how to use this?

**Comment by blink1073** [comment]
Hi!  I'd say use the setubase.py directly.  This was set up as a package not realizing setup_requires doesn't really work.  However with pip 10 you can use a file to accomplish what we want.  On my phone so a vague reply for now. 😀

**Comment by blink1073** [comment]
https://www.python.org/dev/peps/pep-0518/

**Comment by vidartf** [comment]
You can also do:
```cmd
pip install jupyter-packaging
```
and then run
```cmd
python -m jupyter_packaging
```
in the root directory of your package (it will copy over the setupbase.py file).

**Comment by vidartf** [comment]
I guess I wrote that strangely. The way outlined is the way that I've been using it. I'm confused about why it doesn't seem to work for you.

**Comment by vidartf** [comment]
Or rather, that works at least with a local clone and `pip install -e .`. There's been a lot of commits since the last release though.

**Comment by ian-r-rose** [comment]
@vidartf Thanks! Yes, our problem was that we had tried with the last-published version on PyPI, in which that doesn't work. Once we tried with a local clone it worked as expected.

**Comment by mpacer** [comment]
Yep — it works on the master branch… 

But, I'm going to probably send in a few PRs soon to improve the docs and rely more on pypa utilities… we should definitely get a new release out there soon. Happy to take lead on that if no one else wants to.

**Comment by vidartf** [comment]
With pip 10 released, it is now a lot more feasible to depend on this package! @blink1073 Would you mind publishing the latest version to pypi, or giving me the rights to do it (maybe both)?

**Comment by blink1073** [comment]
@vidartf, I gave you the rights.

**Comment by blink1073** [comment]
The action item here is now to update the readme with instructions for use with `pyproject.toml`.  Here is an example: https://github.com/jupyterlab/extension-cookiecutter-ts/blob/master/%7B%7Bcookiecutter.extension_name%7D%7D/pyproject.toml
