### ISSUE TITLE
`ensure_python` should use pypa packaging utilities

### ISSUE THREAD

**Issue by mpacer** [jupyter/jupyter-packaging#24]
Specifically, we should be using the same logic that setuptools is using to parse python_requires, even if we allow a list of arguments to be passed in.

That ends up calling [`SpecifierSet`](https://github.com/pypa/packaging/blob/master/packaging/specifiers.py#L589) `packaging.specifiers` (in [`check_specifiers`](https://github.com/pypa/setuptools/blob/master/setuptools/dist.py#L178-L187)), but we should probably use [`Specifier`](https://github.com/pypa/packaging/blob/master/packaging/specifiers.py#L275) directly, since we're already passing in a list that doesn't need to be split from a string.

If you want to know why we should be relying on packaging directly… check out the regex inside `Specifier`… and that's what will be called eventually from inside setuptools.

**Comment by vidartf** [comment]
I agree that this seems like a good idea, but what is the right way to import it? 🤔

**Comment by blink1073** [comment]
Removing in favor of using `python_requires` in #46
