### ISSUE TITLE
`pip install .` is not handling any files

### ISSUE THREAD

**Issue by blink1073** [jupyter/jupyter-packaging#39]
Needs a test that makes sure both the python files and any data_files are handled properly on an install and uninstall, and that they are present in an `sdist` as well.

**Comment by Zsailer** [comment]
Solving in #41.

**Comment by vidartf** [comment]
I thought #41 only touched the develop install files, but this issue seems to be a non-develop install?

**Comment by blink1073** [comment]
We tested both in #41
