### ISSUE TITLE
Nested folders in data_files are not working

### ISSUE THREAD

**Issue by blink1073** [jupyter/jupyter-packaging#50]
The following config does not work:

```python
data_files_spec = [
    ('etc/jupyter/jupyter_server_config.d',
     'jupyter-config/jupyter_server_config.d', 'jupyterlab.json'),
]
```

The file does not get copied.   We need our tests to include nested folders in the second argument and account for them.

**Comment by vidartf** [comment]
Isn't this why the last argument is a glob? I'm not sure if I understand the full folder structure that is implied in the issue description.
