### ISSUE TITLE
Entry point for setupbase copying

### ISSUE THREAD

**Issue by vidartf** [jupyter/jupyter-packaging#7]
It would be nice if this package registered an entry point (or maybe a `__main__.py`) which copied the setupbase to the current directory. Then it would also be easier to automate this task, e.g. with a custom local script:
```bash
$ pip install -u jupyter-packaging

$ python -m jupyter-packaging
OR
$ jupyter-package-init ./
```

**Comment by blink1073** [comment]
Fixed by #8.
