### ISSUE TITLE
is_stale is unreliable

### ISSUE THREAD

**Issue by vidartf** [jupyter/jupyter-packaging#9]
If I add the `node_modules` folder of an npm package for caching on e.g. Travis CI, Travis will create the folder during set up:

```
Setting up build cache
[...]
fetching master/cache--python-3.4.tgz
could not download cache

adding /home/travis/build/[...]/node_modules to cache
creating directory /home/travis/build/[...]/node_modules
```

This will cause `is_stale` in [this line](https://github.com/jupyter/jupyter-packaging/blob/88f3d10a0ef0229a56f203937f511eb0cc91efe9/jupyter_packaging/setupbase.py#L202) to give the wrong result for the `node_modules` folder, preventing `npm install` from running. This is because the `mtime` of the `node_modules` folder will be very recent.

**Comment by vidartf** [comment]
Actually, maybe `node_modules` should not be cached? I guess `~/.npm` should be cached instead(?).

**Comment by blink1073** [comment]
Hmm, we could `touch` the `package.json` file to make sure it is more recent, or try caching `~/.npm`.

**Comment by vidartf** [comment]
Also, it turns out `is_stale(build_dir, source_dir)` won't work if the source file modified is not in the root of `source_dir` (mtimes doesn't propagate up). So `is_stale` should be made recursive here (and folder mtimes should probably not be considered?).

**Comment by blink1073** [comment]
It seems like `is_stale` is always going to be a whack-a-mole, perhaps we should just remove the notion altogether?

**Comment by vidartf** [comment]
I'm going to attempt a fix as a PR, and then you can consider that vs. a removal.
