### ISSUE TITLE
Non-executable files with shebangs

### ISSUE THREAD

**Issue by frenzymadness** [jupyter/jupyter-packaging#95]
There are some files like this one

https://github.com/jupyter/jupyter-packaging/blob/cb748a474670289dd1196cf4f1a7081e7a51a560/jupyter_packaging/__init__.py#L1

where there is no reason to run them as Python scripts, but they still have shebang. Could you please remove them? Or is there anything I don't see?

**Comment by blink1073** [comment]
> Could you please remove them?

Would you like to submit PRs for this and #94?

**Comment by frenzymadness** [comment]
Yes, it's on my to-do list. Will do it soon.
